language: node_js
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "xZc8nkWCmvUjTjEMsdE0S02QJxrCd7dKVqH6Cdib1gboEKG7BI1bKwZ6oRn56IruN14GTklaMrnwgD4T199J1stkLyk4gLv8OKZH8iRwLNLo2XeEEXdzEit8W9uY3owbNSIi8PK7jm6mn4YXQJCC2rTeDMThVIqHt0UazmHmHTaUQ8QkG9yLSZJJKGtiSwo8F52MswRhyDOhOlZl40bvOYQvvhq4fzZCdynRA3EjpN8ycWc3CWKw4gj0DZN8H79nj8qg58+0wlcRej+ZPZOwj5LZgZ9wTrMTHoiKTINjly7CW6nEMRz6rlUPDJj2RwBS8jGiukvpJvrqbXGq0iicgkUP7t+y/cWdXiO6aW6uL7yhqDfxxDhix5wMk6VTYPqQm9bJXO0ziMjiP5IRwmW71bd0hpTObH8jmV8O2Bn66O7IKKAR8c4kcjH5I2O9Fjwiou5FyZdDCWOdvyR6Smih+Cwso0Nv0wbxr6I3/WEIfh07GpTYpvs4JQ7813PhCjRqbPqBLJ7A2IkkJLjYEDeP7MMBZfQxmomlGSmhaPypBYOs/pjUE3eWCYywZjOsvsp2Slr0j4wc91llm7/2Fl1h+vBaE4MfpUJNZB11IvH+aFsXSDHBXKXkdzcGwmi+zw5U83sSKUgFGHYWEVtr7xCT31K0meXfWGmhgq4Gn0LZSJ0="
  api_key: # 0167
    secure: "Xz+eraqrQ5vlOk/ilxzCXQvcA0BROeZSED52sY/uz4HPWtZLAOht8JJz2u/lMj5R8zV1KH8RZ9nTxRsk3sALomRhpqpspdutAUoZsODFQb2re8vznouyqf894VR+EI6thhH3qlaCWx8FQ6ZIxetgMTYDTGTgZy8EVHfjpa2ki3XPdvJBdIejqrWMzjYkTBtS4Ap28OXwnSC+c1vnjClrowRJdJhM7qBoosucb3pmvMm2JjVkb99WU3yZbUsve0tR40A34h3AYflX86rc1nmI+GR3IWJ7QRYYIhusd4qUPAUQfUET5mJx3WGyoPkRWdJfSstM/CHj+vNnbCjtOMS2VmZaOkzxO5asKKr+nxuDmqE+5aDG3xRRh64t3O6+ealrmSzYVoyIghFRWAYG28o6PmJJiXw+9yZ+kbFXqAsoJA6/Z8I1sr8EhlQbLwxQHA/ktEhKCgDwdseMseq10Jc1fsRbGRtXKIH4gOLXrN8xfdV6zx/yavHr75jevAfRorGQsLad6r79t+cTZU7Jo6Qm5IULq/IbnXXqDQcdrANrkUO3zMerPRxVUiKv6uCMIiCqBPvbU78pHy8VzUO/Gefz6sPKEXDPEzG4c7JQEY2iD0BmLTvm8fOdBtypYqNQvz1RX5e3h1qrNGmS7VRQcmDn5p/LfHGWl3CCgmi2Dv/7evU="
  on:
    tags: true
    node: lts/*
